name: record_linux
description: Dummy package to suppress record_linux warnings (not used on Android/iOS)
version: 0.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
