// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqYfQlCih9M13_WfwW8ccEn8DBx8oVraE',
    appId: '1:227172104482:web:6271cf8de63201ab778d7b',
    messagingSenderId: '227172104482',
    projectId: 'astrobharatai-db3cf',
    authDomain: 'astrobharatai-db3cf.firebaseapp.com',
    storageBucket: 'astrobharatai-db3cf.firebasestorage.app',
    measurementId: 'G-1MMN57RJ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt2-eGlgwpqHQR8YAALwevPCDAH2wY76M',
    appId: '1:227172104482:android:ebe4822c8dc945a4778d7b',
    messagingSenderId: '227172104482',
    projectId: 'astrobharatai-db3cf',
    storageBucket: 'astrobharatai-db3cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOUS9kg3RGj5achUzZ6oh4RpwsQ5fbIc',
    appId: '1:227172104482:ios:80125179aa8f3f8c778d7b',
    messagingSenderId: '227172104482',
    projectId: 'astrobharatai-db3cf',
    storageBucket: 'astrobharatai-db3cf.firebasestorage.app',
    iosBundleId: 'com.astrobharatai.astrouser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOUS9kg3RGj5achUzZ6oh4RpwsQ5fbIc',
    appId: '1:227172104482:ios:80125179aa8f3f8c778d7b',
    messagingSenderId: '227172104482',
    projectId: 'astrobharatai-db3cf',
    storageBucket: 'astrobharatai-db3cf.firebasestorage.app',
    iosBundleId: 'com.astrobharatai.astrouser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJ0F9m6SNYKHrcs8O5sRl2LQ7ia1gm3Y',
    appId: '1:227172104482:web:c714b93ef366900b778d7b',
    messagingSenderId: '227172104482',
    projectId: 'astrobharatai-db3cf',
    authDomain: 'astrobharatai-db3cf.firebaseapp.com',
    storageBucket: 'astrobharatai-db3cf.firebasestorage.app',
    measurementId: 'G-1H1PMRYZPW',
  );
}
