platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# The path to the flutter_tools podhelper script.
def flutter_root
  generated_xcconfig_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcconfig_path)
    raise "#{generated_xcconfig_path} must exist. If you're running pod install manually, make sure \`flutter pub get\` is executed first"
  end

  File.foreach(generated_xcconfig_path) do |line|
    matches = line.match(/\AFLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  
  # If FLUTTER_ROOT not found, try to extract from environment or use default
  ENV['FLUTTER_ROOT'] || raise("FLUTTER_ROOT not found. Please run `flutter pub get` first")
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Fix for pods that have lower deployment target
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
  
  # Force all pods to use iOS 15.0 minimum
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
end
