name: iOS Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          channel: 'stable'

      - name: Verify Flutter
        run: flutter doctor

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          export FLUTTER_ROOT=$HOME/hostedtoolcache/flutter/stable-3.41.2-arm64
          pod install --repo-update

      - name: Build iOS (No Code Sign)
        run: flutter build ios --no-codesign -v
